### ISSUE TITLE
symbols and nested symbols bug

### ISSUE THREAD

**Issue by zeroxme** [Qordobacode/qordoba-for-sketch#2]
Is there a plan for fixing symbols and nested symbols bug?
It's kinda critical to those who use symbols heavily.

**Comment by GoldenZero** [comment]
Hi @zeroxme ,
We are going to support the sketch symbols in the new release, which should be ready very soon

**Comment by zeroxme** [comment]
@GoldenZero Awesome!
Thanks for your quick reply 👍

**Comment by GoldenZero** [comment]
@zeroxme the new version V2.2 is released with Support the symbol translations, you can choose to detach the symbols in the new translated page, or use the override sketch feature to have the content translated.

**Comment by zeroxme** [comment]
Awesome I'll give it a try!
